export   const members = [
    {
      id: "1",
      name: "Sarah Johnson",
      email: "sarah@example.com",
      phone: "+1 (555) 456-7890",
      level: "Intermediate",
      joinedOn: "Mar 15, 2023",
      image: "",
    },
    {
      id: "2",
      name: "Michael Brown",
      email: "michael@example.com",
      phone: "+1 (555) 567-8901",
      level: "Advanced",
      joinedOn: "Apr 2, 2023",
      image: "",
    },
    {
      id: "3",
      name: "Emma Wilson",
      email: "emma@example.com",
      phone: "+1 (555) 678-9012",
      level: "Beginner",
      joinedOn: "Apr 20, 2023",
      image: "",
    },
    {
      id: "4",
      name: "Alex Kim",
      email: "alex@example.com",
      phone: "+1 (555) 123-4567",
      level: "Intermediate",
      joinedOn: "Jan 20, 2023",
      image: "",
    },
    {
      id: "5",
      name: "Maria Lopez",
      email: "maria@example.com",
      phone: "+1 (555) 234-5678",
      level: "Beginner",
      joinedOn: "Feb 5, 2023",
      image: "",
    },
    {
      id: "6",
      name: "John Davis",
      email: "john@example.com",
      phone: "+1 (555) 345-6789",
      level: "Advanced",
      joinedOn: "Feb 10, 2023",
      image: "",
    },
]